### ISSUE TITLE
Questions about installing C++ libraries

### ISSUE THREAD

**Issue by 4AMZGGO1** [zju3dv/SMAP#17]
The instruction"python setup.py install" error:
running install
running bdist_egg
running egg_info
writing dapalib.egg-info/PKG-INFO
writing dependency_links to dapalib.egg-info/dependency_links.txt
writing top-level names to dapalib.egg-info/top_level.txt
reading manifest file 'dapalib.egg-info/SOURCES.txt'
writing manifest file 'dapalib.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_ext
Traceback (most recent call last):
  File "setup.py", line 19, in <module>
    cmdclass = {'build_ext': BuildExtension}
  File "/home/dell/anaconda3/envs/torch11/lib/python3.7/site-packages/setuptools/__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)
  File "/home/dell/anaconda3/envs/SMAP/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/dell/anaconda3/envs/SMAP/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/home/dell/anaconda3/envs/SMAP/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/dell/anaconda3/envs/torch11/lib/python3.7/site-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/home/dell/anaconda3/envs/torch11/lib/python3.7/site-packages/setuptools/command/install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "/home/dell/anaconda3/envs/SMAP/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/dell/anaconda3/envs/SMAP/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/dell/anaconda3/envs/torch11/lib/python3.7/site-packages/setuptools/command/bdist_egg.py", line 172, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/home/dell/anaconda3/envs/torch11/lib/python3.7/site-packages/setuptools/command/bdist_egg.py", line 158, in call_command
    self.run_command(cmdname)
  File "/home/dell/anaconda3/envs/SMAP/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/dell/anaconda3/envs/SMAP/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/dell/anaconda3/envs/torch11/lib/python3.7/site-packages/setuptools/command/install_lib.py", line 11, in run
    self.build()
  File "/home/dell/anaconda3/envs/SMAP/lib/python3.7/distutils/command/install_lib.py", line 107, in build
    self.run_command('build_ext')
  File "/home/dell/anaconda3/envs/SMAP/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/dell/anaconda3/envs/SMAP/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/dell/anaconda3/envs/torch11/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 78, in run
    _build_ext.run(self)
  File "/home/dell/anaconda3/envs/torch11/lib/python3.7/site-packages/Cython/Distutils/old_build_ext.py", line 186, in run
    _build_ext.build_ext.run(self)
  File "/home/dell/anaconda3/envs/SMAP/lib/python3.7/distutils/command/build_ext.py", line 340, in run
    self.build_extensions()
  File "/home/dell/anaconda3/envs/SMAP/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 257, in build_extensions
    self._check_abi()
  File "/home/dell/anaconda3/envs/SMAP/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 399, in _check_abi
    check_compiler_abi_compatibility(compiler)
  File "/home/dell/anaconda3/envs/SMAP/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 187, in check_compiler_abi_compatibility
    if not check_compiler_ok_for_platform(compiler):
  File "/home/dell/anaconda3/envs/SMAP/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 163, in check_compiler_ok_for_platform
    which = subprocess.check_output(['which', compiler], stderr=subprocess.STDOUT)
  File "/home/dell/anaconda3/envs/SMAP/lib/python3.7/subprocess.py", line 411, in check_output
    **kwargs).stdout
  File "/home/dell/anaconda3/envs/SMAP/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['which', 'x86_64-conda_cos6-linux-gnu-c++']' returned non-zero exit status 1.

**Comment by raypine** [comment]
What's your environments (gcc, pytorch, cuda) ?

**Comment by 4AMZGGO1** [comment]
> What's your environments (gcc, pytorch, cuda) ?
My pytorch version is 1.4.0.
And I tried several gcc version,including 6.1, 7.3, 9.3. 
cuda version is 9.0.

**Comment by raypine** [comment]
Maybe the conda gxx problem. 
After searching your problem, I find a solution:
```
conda install gxx_linux-64
```
You can have a try.

**Comment by 4AMZGGO1** [comment]
> Maybe the conda gxx problem.
> After searching your problem, I find a solution:
> 
> ```
> conda install gxx_linux-64
> ```
> 
> You can have a try.

I tried it. But it seems that there are still something wrong:
"error: command '/home/dell/anaconda3/envs/SMAP/bin/x86_64-conda-linux-gnu-c++' failed with exit status 1"
